- name: configuring catalogue 
  become: yes
  hosts: catalogue
  tasks:
  - name: disabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y

  - name: enabling nodejs:20 version
    ansible.builtin.shell: dnf module enable nodejs:20 -y

  - name: Installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: creating a directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: downloading catalogue url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: extracting catalogue url
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Installing npm package
    community.general.npm:
      path: /app

  - name: copying catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: starting catalogue service
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: yes
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: loading content into mongodb
    ansible.builtin.shell: mongosh --host mongodb.autonagar.in </app/db/master-data.js
    when: catalogue_output.stdout | int < 0