- name: configuring shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: creating a directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: downloading shipping url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: extracting shipping url
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: installing maven dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  - name: renaming jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app


  - name: copying shipping.service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: starting shipping.service file
    ansible.builtin.service:
      name: shipping.service
      state: started
      enabled: yes

  - name: daemon_reloading
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: importing data into mysql
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.autonagar.in
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: restarting shipping service
    tag:
    - import
    ansible.builtin.service:
      name: shipping.service
      state: restarted
